spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5446/retail-rocket
    password: admin
    properties:
      schema: retail_schema
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: retail-rocket
  security:
    user:
      name: user
      password: admin
server:
  port: '8086'
jwt:
  secret:
    key: 'BqwgfBrfGspp6/FiOHQD9fkiSbfTyDzERmx4xkW5Eug='
logging:
  level:
    root: info
    com.example.retail_rocket: debug